- name: Integrando Worker nodes no cluster
  hosts: workers
  become: yes
  gather_facts: yes

  tasks:
   - name: Copia o comando de Kube join para os workers - {{ inventory_hostname }}
     copy:
       src: /tmp/kubernetes_join_command
       dest: /tmp/kubernetes_join_command
       mode: 0777

   - name: Join do worker - {{ inventory_hostname }}
     become: yes
     command: sh /tmp/kubernetes_join_command
     register: joined_or_not
   - name:
     debug:
       msg: "{{ joined_or_not.stdout }}"
